# Generated by Django 4.1.5 on 2023-03-03 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waiter', '0003_payment_orderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableServer',
            fields=[
                ('tableID', models.AutoField(primary_key=True, serialize=False)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.order')),
                ('waiterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TableServer',
            },
        ),
    ]
