# Generated by Django 4.1.5 on 2023-03-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0004_tableserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
