# Generated by Django 4.1.5 on 2023-03-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0005_alter_payment_paymentamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='dateOfPayment',
            field=models.DateField(auto_now=True),
        ),
    ]
