# Generated by Django 4.1.5 on 2023-02-27 17:01

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('price', models.FloatField(null=True)),
                ('calories', models.IntegerField(null=True)),
                ('alergies', models.TextField()),
                ('description', models.TextField()),
                ('course', models.CharField(choices=[('Starter', 'Starter'), ('Main', 'Main'), ('Dessert', 'Dessert'), ('Side', 'Side'), ('Drink', 'Drink')], default='Main', max_length=10)),
                ('dietRequirements', models.CharField(choices=[('None', 'None'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian')], default='None', max_length=10)),
                ('ID', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'MenuItem',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Placed', 'Placed'), ('Confirmed', 'Confirmed'), ('Prepared', 'Prepared'), ('Delivered', 'Delivered')], default='Placed', max_length=10)),
                ('timeOfOrder', models.TimeField(auto_now=True)),
                ('orderedItems', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('requestID', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=100, null=True)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'HelpRequest',
            },
        ),
    ]
