# Generated by Django 4.1.5 on 2023-02-07 00:14

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('calories', models.IntegerField()),
                ('cuisine', models.CharField(max_length=10, null=True)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('alergies', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('description', models.CharField(max_length=300)),
                ('course', models.CharField(choices=[('Starter', 'Starter'), ('Main', 'Main'), ('Dessert', 'Dessert'), ('Side', 'Side'), ('Drink', 'Drink')], default='Main', max_length=10)),
                ('dietRequirements', models.BooleanField(choices=[('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian')], max_length=10, null=True)),
            ],
            options={
                'db_table': 'MenuItem',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Placed', 'Placed'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered')], max_length=10)),
                ('timeOfOrder', models.TimeField()),
                ('orderedItems', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
