# Generated by Django 4.1.5 on 2023-01-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='cuisine',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
