# Generated by Django 4.1.5 on 2023-02-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_menuitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='cuisine',
        ),
    ]
