# Generated by Django 4.1.5 on 2023-02-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_menuitem_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Confirmed', 'Confirmed'), ('Prepared', 'Prepared'), ('Delivered', 'Delivered')], default='Placed', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='timeOfOrder',
            field=models.TimeField(auto_now=True),
        ),
    ]
