# Generated by Django 4.1.5 on 2023-02-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_menuitem_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PL', 'Placed'), ('CO', 'Confirmed'), ('DE', 'Delivered')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='timeOfOrder',
            field=models.TimeField(auto_now=True),
        ),
    ]
