# Generated by Django 4.1.5 on 2023-01-21 19:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderedItems',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
