# Generated by Django 4.1.5 on 2023-03-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_order_ordereditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='imgurl',
            field=models.URLField(default='https://drive.proton.me/urls/ZSNK82MYCM#RLw8zlaNRCxu'),
        ),
        migrations.AddField(
            model_name='order',
            name='notificationSent',
            field=models.BooleanField(default=False),
        ),
    ]
