# Generated by Django 4.1.5 on 2023-03-11 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_order_ordereditems'),
    ]

    operations = [
    ]
