# Generated by Django 4.1.5 on 2023-02-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_helprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='alergies',
            field=models.TextField(),
        ),
    ]
