# Generated by Django 4.1.5 on 2023-03-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_menuitem_imgurl_order_notificationsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateOfOrder',
            field=models.DateField(auto_now=True),
        ),
    ]
