# Generated by Django 4.1.5 on 2023-03-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20230311_2238'),
        ('project', '0006_order_dateoforder'),
    ]

    operations = [
    ]
