# Generated by Django 4.1.5 on 2023-01-21 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_alter_menuitem_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
