# Generated by Django 4.1.5 on 2023-03-22 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_merge_0005_auto_20230311_2238_0006_order_dateoforder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='alergies',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='calories',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='imgurl',
            field=models.URLField(default='https://i.postimg.cc/PqLn57Cr/No-Image-Available.png'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
