# Generated by Django 4.1.5 on 2023-02-02 14:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_menuitem_course_menuitem_dietrequirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='dietRequirements',
            field=models.CharField(choices=[('None', 'None'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
