# Generated by Django 4.1.5 on 2023-01-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_menuitem_course_menuitem_dietrequirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timeOfOrder',
            field=models.TimeField(auto_now=True),
        ),
    ]
