# Generated by Django 4.1.5 on 2023-02-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_menuitem_dietrequirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='ingredients',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
