# Generated by Django 4.1.5 on 2023-01-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_order_timeoforder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PL', 'Available'), ('CO', 'Reserved'), ('DE', 'Checked Out')], max_length=10),
        ),
    ]
