# Generated by Django 4.1.5 on 2023-02-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_menuitem_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='ID',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
