# Generated by Django 4.1.5 on 2023-01-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PL', 'Placed'), ('CO', 'Confirmed'), ('DE', 'Delivered')], max_length=2),
        ),
    ]
